spring:
  application:
    name: SpringAITest
  ai:
    openai:
      base-url: https://api.deepseek.com
      api-key: ${OPEN_AI_KEYS}
      chat:
        options:
          model: deepseek-chat
      embedding:
        options:
          model: text-embedding-v3
          dimensions: 1024
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:7b
    mcp:
      client:
        enabled: true
        name: test
        version: 1.0.0
        initialized: true
        request-timeout: 20s
        type: async
        root-change-notification: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hmdp?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
server:
  port: 8080
logging:
  level:
    org.springframework.ai: debug
    com.lucius.springaitest: debug